### ISSUE TITLE
Get Request Context

### ISSUE THREAD

**Issue by hcs-bernardo-rufino** [tonybaloney/ants-azure-demos#9]
I've been using this and it works really nice.

I have a problem now that i need to capture the context from que function (to get context.function_directory so i can make it work with a file share).

Any hint on how to make it work in this?

> def main(req: func.HttpRequest, context: func.Context) -> func.HttpResponse:
>     return AsgiMiddleware(app).handle(req, context)

**Comment by tonybaloney** [comment]
Moved issue to https://github.com/Azure/azure-functions-python-worker/issues/1082
